### ISSUE TITLE
No space between attributes.

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/nexus-fall-2017#1]
https://github.com/redacademy/nexus-fall-2017/blob/774bd03e457d058a03020df6c68e3057c4ed1de2/themes/nexus/header.php#L31

W3C validator issue.

Just need to add a space e.g.
```
<a href="<?php echo home_url();?> "class="header-logo"></a>
```

**Comment by ColinYaremko** [comment]
<a href="<?php echo home_url();?> " class="header-logo"></a>
