### ISSUE TITLE
Make Footer Nav accessible to Client

### ISSUE THREAD

**Issue by rcass** [redacademy/nexus-fall-2017#13]
Right now the footer navigation is hard coded into the footer.php. Since this is something that a client typically wants to change I would make this accessible in the wordpress admin.

The best way to do this would be to register a new menu.

Check [this article](http://www.wpbeginner.com/wp-themes/how-to-add-custom-navigation-menus-in-wordpress-3-0-themes/) out or the [codex](https://codex.wordpress.org/Navigation_Menus) for more info

**Comment by ColinYaremko** [comment]
Converted to use the Menu selection (same as the main nav but styled differently for the footer)
