### ISSUE TITLE
Avoid use of empty divs

### ISSUE THREAD

**Issue by rcass** [redacademy/nexus-fall-2017#14]
I saw this is more than one php file, but using empty divs for just css sake should be avoided.

Here are some examples:
![screen shot 2017-12-14 at 8 51 39 pm](https://user-images.githubusercontent.com/5028555/34027307-a28a111e-e110-11e7-8a55-1361a112c60d.png)

Basically we should try to use the elements on the page rather than creating markup just for css sake.  Means getting a bit clever with your css, but we can troubleshoot together if you are really stuck.

**Comment by ColinYaremko** [comment]
Used &::after.
