### ISSUE TITLE
Button shouldn't be nested inside of an <a> element

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/nexus-fall-2017#2]
https://github.com/redacademy/nexus-fall-2017/blob/774bd03e457d058a03020df6c68e3057c4ed1de2/themes/nexus/header.php#L35

<button> shouldn't be nested inside of an <a>
and vice versa
<a> shouldn't be nested inside of <button>

Since they both have similar behaviour it's redundant and throws an error when being run through the W3C validator.

**Comment by ColinYaremko** [comment]
Ongoing

**Comment by Sstobo** [comment]
fixed
