### ISSUE TITLE
Duplicate ID primary-menu

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/nexus-fall-2017#3]
https://github.com/redacademy/nexus-fall-2017/blob/774bd03e457d058a03020df6c68e3057c4ed1de2/themes/nexus/header.php#L34-L43

Looks like the primary menu is being used twice, it's probably for a reason e.g. mobile menu. Just be careful as they should have unique ids. If one if for mobile you could use primary-menu-mobile or mobile-menu as the id

**Comment by Sstobo** [comment]
fixed
