### ISSUE TITLE
Element h3 not allowed as child of element i

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/nexus-fall-2017#4]
https://github.com/redacademy/nexus-fall-2017/blob/774bd03e457d058a03020df6c68e3057c4ed1de2/themes/nexus/front-page.php#L123

You could try having the icon on it's own and the h3 after e.g.

<div><i class="bc fa fa-map-marker fa-4x"></i><h3 class="show bc-text">British Columbia</h3></div>

**Comment by ColinYaremko** [comment]
Tried to move it around and it loses the effect of displaying the name of the province while hovering/clicking.
