### ISSUE TITLE
Replace get_bloginfo( 'template_directory' ) with get_template_directory_uri()

### ISSUE THREAD

**Issue by rcass** [redacademy/nexus-fall-2017#9]
Need to change these in about.php. 
![screen shot 2017-12-14 at 8 32 11 pm](https://user-images.githubusercontent.com/5028555/34026915-1ad1ceb2-e10e-11e7-93c8-b8dc42a8a1b4.png)

**Comment by ColinYaremko** [comment]
Changed.  Saved.  Tested.  Committed. Complete. :-)
